'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../hall-of-fame');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const rows = index.match(/<tr>[\s\S]*?<\/tr>/g).filter(row => row.includes('<b>CopyIdentityBleed</b>'));
assert.equal(rows.length, 1);
const cells = rows[0].match(/<td\b[^>]*>[\s\S]*?<\/td>/g);
assert.equal(cells.length, 8);
assert.match(cells[4], /https:\/\/github.com\/xet7/);
assert.equal((cells[5].match(/GoldStar.png/g) || []).length, 3);
assert.match(cells[6], /<details><summary>Process<\/summary>/);
assert.match(cells[7], /<details><summary>Details<\/summary>/);
const page = fs.readFileSync(path.join(root, 'copyidentitybleed/index.html'), 'utf8');
assert.doesNotMatch(page, /<details>/);
assert.match(page, /not yet released/);
assert.match(page, /Server card copies now validate destination board, list and swimlane ownership/);
// Board-copy property merging is now fixed; template writes remain under review.
assert.match(page, /client-side template writes, direct Rules writes/);
assert.match(page, /Properties outside title, sort, type, without-cards and card selection are now refused/);
assert.match(page, /https:\/\/github\.com\/wekan\/wekan\/commit\/94931c7ab/);
assert.doesNotMatch(page, /board-copy property merging/);
assert.match(page, /not tested/);
assert.match(page, /without attack records or account blocking/);
assert.match(page, /github.com\/wekan\/wekan\/commit\/[a-f0-9]{9,40}/);
console.log('CopyIdentityBleed Hall of Fame: structure, attribution, fix evidence and limits pass');
