'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../hall-of-fame');
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const rows = index.match(/<tr>[\s\S]*?<\/tr>/g).filter(row => row.includes('<b>TrayBleed</b>'));
assert.equal(rows.length, 1);
const cells = rows[0].match(/<td\b[^>]*>[\s\S]*?<\/td>/g);
assert.equal(cells.length, 8);
assert.equal(cells[0], '<td valign="top">-</td>');
assert.match(cells[1], /fa-tint" style="color: red;"/);
assert.equal(cells[3], '<td valign="top">2026-10-02</td>');
assert.match(cells[4], /^<td valign="top"><b><a href="https:\/\/github.com\/xet7">xet7<\/a><\/b><\/td>$/);
// Found and fixed by the maintainer, no GHSA: three stars (Audit-Stars.md).
assert.equal((cells[5].match(/GoldStar.png/g) || []).length, 3);
assert.match(cells[6], /<details><summary>Process<\/summary>[\s\S]*Found while auditing/);
assert.match(cells[7], /<details><summary>Details<\/summary>/);
assert.match(cells[7], /<a href="traybleed\/">Fix and verification<\/a>/);
// Newest first: above HookUrlBleed.
assert.ok(index.indexOf('<b>TrayBleed</b>') < index.indexOf('<b>HookUrlBleed</b>'));
const page = fs.readFileSync(path.join(root, 'traybleed/index.html'), 'utf8');
assert.doesNotMatch(page, /<details>/);
assert.match(page, /not yet released/);
assert.match(page, /CWE-639/);
assert.match(page, /authz.notification-tray/);
assert.match(page, /profile.notifications/);
assert.match(page, /https:\/\/github\.com\/wekan\/wekan\/commit\/cd07d8db18/);
assert.match(page, /https:\/\/github\.com\/wekan\/wekan\/commit\/c15f9486d8/);
assert.match(page, /Admin Panel → Problems/);
assert.match(page, /<h2>Detection<\/h2>\n<p>[^<]*summarized as TrayBleed/);
console.log('TrayBleed Hall of Fame: structure, attribution, fix evidence and limits pass');
